### PR TITLE
Add changes to scale the effective batch size of the model

### LINKED ISSUE #1: Multi-GPU training
This issues is to track progress on multi-GPU training on slurm clusters

### PR DESCRIPTION
**Pull request by MatthijsMars**
Closes #1 

Adds methods to scale up the effective batch size of the model. This includes a script to find the largest batch size that fits on your current GPU; `find_batch_size.py`. Also it includes the option to accumulate gradients over several batches by setting in the config file: 

```
batch_size: 8
accumulate_grad_batches: 2 # only updates model after 2 batches per GPU
```

The effective batch size of the model is then: n_gpus * batch_size *  accumulate_grad_batches. 

A more detailed description of how the model runs on the multiple GPUs can be found in #1

### CODE REVIEW

**Comment by tobias-liaudat** [comment]
@MatthijsMars Thanks for this PR, it looks good! I'll just aks you two simple things before merging:

- Could you add the info that you wrote in issue #1  into the [comments.md](https://github.com/astro-informatics/rcGAN/blob/dev/comments.md) in a new section.
- Could you create a folder called examples in the repo and add an example slurm job (.sh) for multi GPU training.

**Review by tobias-liaudat — CHANGES_REQUESTED** [review]
See my previous comment

**Comment by JessWhitney** [comment]
Looks good, I agree with the changes Tobias suggested.

**Comment by MatthijsMars** [comment]
@tobias-liaudat I added the text to `comments.md` and provided 2 example scripts for finding the batch size and for doing multi-gpu training. Have a look and merge if it's okay

**Review by JessWhitney — APPROVED** [review]

**Review by tobias-liaudat — APPROVED** [review]
Thanks for the changes, it looks good to me

**Pull request merged**
